force_cast: warning # implicitly
included: # paths to include during linting. `--path` is ignored if present.
    - JSONRequest
disabled_rules:
    - line_length
identifier_name:
    excluded:
        - to
